import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import "./globals.css";

import Image from "next/image";
import Link from "next/link";
import Script from "next/script";
import { HomeIcon, ShoppingCartIcon } from "lucide-react";

import { merchantSchema } from "@/lib/schema";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const merchantDetails = await fetch(
    `https://groww-intern-assignment.vercel.app/v1/api/merchant-metadata`,
    { cache: "no-store" },
  );

  const merchantData = merchantSchema.parse(await merchantDetails.json());

  type Theme = keyof typeof merchantData.theme;

  const theme = Object.fromEntries(
    Object.entries(merchantData.theme).map(([key, value]) => [
      `${key}-groww`,
      value,
    ]),
  );
  console.log(merchantData.theme);

  return (
    <html lang="en" suppressHydrationWarning>
      {/* <Script
        id="theme-style"
        async
        dangerouslySetInnerHTML={{
          __html: `
      const root = document.documentElement;
      const theme = ${JSON.stringify(theme)};
      Object.entries(theme).forEach(([key, value]) => {
        root.style.setProperty(\`\${key}\`, value);
      });
    `,
        }}
      /> */}
      <body
        className={cn(
          "grid min-h-screen w-full bg-background font-sans antialiased lg:grid-cols-[280px_1fr]",
          fontSans.variable,
        )}
      >
        <aside className="hidden border-r bg-background/40 lg:block dark:bg-background/40">
          <div className="sticky top-0 flex flex-col gap-2">
            <div className="flex h-[60px] items-center border-b px-6">
              <Link className="flex items-center gap-2 font-semibold" href="#">
                <Image
                  src={merchantData.merchantLogo}
                  alt="logo"
                  width="24"
                  height="24"
                />
                <span>{merchantData.merchantName}</span>
              </Link>
            </div>
            <div className="flex-1 overflow-auto py-2">
              <nav className="grid items-start px-4 text-sm font-medium">
                <Link
                  className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="#"
                >
                  <HomeIcon className="h-4 w-4" />
                  Home
                </Link>
                <Link
                  className="flex items-center gap-3 rounded-lg bg-background px-3 py-2 text-gray-900 transition-all hover:text-gray-900 dark:bg-background dark:text-gray-50 dark:hover:text-gray-50"
                  href="#"
                >
                  <ShoppingCartIcon className="h-4 w-4" />
                  Checkout
                </Link>
              </nav>
            </div>
          </div>
        </aside>
        <div className="relative flex min-h-screen flex-col">
          <header className="sticky top-0 flex h-14 items-center gap-4 border-b bg-background/40 px-6 backdrop-blur-md lg:h-[60px] dark:bg-background/40">
            <Link className="lg:hidden" href="#">
              <Image
                src={merchantData.merchantLogo}
                alt="logo"
                width="24"
                height="24"
              />
              <span className="sr-only">{merchantData.merchantName}</span>
            </Link>
          </header>
          <main className="flex flex-1 flex-col gap-4 overflow-auto p-4 md:gap-8 md:p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
